"""Create followers_assoc table

Revision ID: 5dd65d07acc9
Revises: 8ebc5ea3592e
Create Date: 2020-09-19 10:23:20.911672

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5dd65d07acc9"
down_revision = "8ebc5ea3592e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers_assoc",
        sa.Column("follower", sa.Integer(), nullable=False),
        sa.Column("followed_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["followed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower"],
            ["users.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("followers_assoc")
    # ### end Alembic commands ###
