"""Create followers_assoc table

Revision ID: df5ed60be29a
Revises: 8ebc5ea3592e
Create Date: 2020-09-19 20:21:12.747457

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "df5ed60be29a"
down_revision = "8ebc5ea3592e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "followers_assoc",
        sa.Column("follower", sa.Integer(), nullable=False),
        sa.Column("followed_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["followed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("follower", "followed_by"),
    )
    op.create_index(
        op.f("ix_followers_assoc_followed_by"),
        "followers_assoc",
        ["followed_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_followers_assoc_follower"),
        "followers_assoc",
        ["follower"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_followers_assoc_follower"), table_name="followers_assoc")
    op.drop_index(op.f("ix_followers_assoc_followed_by"), table_name="followers_assoc")
    op.drop_table("followers_assoc")
    # ### end Alembic commands ###
