"""Create tags table

Revision ID: f7cbee279cef
Revises: df5ed60be29a
Create Date: 2020-09-19 22:01:13.833886

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f7cbee279cef"
down_revision = "df5ed60be29a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("tag", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("tag"),
    )
    op.create_index(op.f("ix_tags_tag"), "tags", ["tag"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tags_tag"), table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
